@GaitSession_API_HostAddress = http://localhost:5106

### Test Subject Service (Root Endpoint)
GET {{GaitSession_API_HostAddress}}/gaitsession
Accept: application/json

### Get Raw GaitSession (c3d filer: "221010 ID6_S119.c3d", "Run_Comfortable1.c3d" eller "Walk_Comfortable1.c3d" )
GET {{GaitSession_API_HostAddress}}/gaitsession/raw/Walk_Comfortable1.c3d
Accept: application/json